//
// Created by Santiago Alvarez Vargas on 2019-03-13.
//

#ifndef PULPOBOT_COMMON_EVENT_DEFINITIONS_H
#define PULPOBOT_COMMON_EVENT_DEFINITIONS_H

#define COMMON_BASE_EVENT_ID 0
#define COMMON_WINDOW_CLOSE_EVENT_ID COMMON_BASE_EVENT_ID + 1
#define COMMON_WINDOW_KEY_PRESSED_EVENT_ID COMMON_BASE_EVENT_ID + 2
#define COMMON_WINDOW_FUNCTION_KEY_PRESSED_EVENT_ID COMMON_BASE_EVENT_ID + 3


#endif //PULPOBOT_COMMON_EVENT_DEFINITIONS_H
